name = "IdentityMatrix"
uuid = "8edef7da-e1b3-479c-b6e4-7e7cac36144b"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
